/**
 * ToolForge — Runtime Tool Creation Engine
 *
 * 让 Agent 在运行时创建、加载、管理新工具。
 * 核心理念：Agent 已有 write_file 和 execute_shell，但无法将写出的代码
 * 变为自己的能力。ToolForge 就是这座桥梁——动态 import + Tool 接口
 * 验证 + 即时注册到 ToolExecutor。
 *
 * 生物学类比：神经可塑性 (neuroplasticity)——新突触在已有框架内生长。
 */

import { mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync, unlinkSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { homedir } from 'node:os';
import type { Tool, ToolResult } from './tool-executor.js';
import { ToolExecutor } from './tool-executor.js';

// ── Types ──

/**
 * 动态创建的工具元数据
 */
export interface ForgedToolMeta {
  name: string;
  description: string;
  filePath: string;
  createdAt: number;
  lastUsedAt: number;
  callCount: number;
  failureCount: number;
}

/**
 * ToolForge 操作结果
 */
export interface ForgeResult {
  success: boolean;
  data?: {
    name: string;
    description: string;
    filePath: string;
  };
  error?: string;
}

/**
 * Agent 传入的代码需要符合此接口
 */
interface DynamicToolModule {
  default?: {
    name: string;
    description: string;
    execute: (params: unknown) => Promise<ToolResult>;
  };
  name?: string;
  description?: string;
  execute?: (params: unknown) => Promise<ToolResult>;
}

// ── Code Template ──

/**
 * 动态工具的代码模板
 * Agent 只需提供 execute 函数体，模板负责包装为合法 Tool 模块。
 */
export const TOOL_TEMPLATE = `// Auto-generated by ToolForge
// Tool: {{NAME}}
// Description: {{DESCRIPTION}}
// Created: {{DATE}}

export default {
  name: '{{NAME}}',
  description: '{{DESCRIPTION}}',
  async execute(params) {
    const p = typeof params === 'object' && params !== null ? params : {};
    {{BODY}}
  }
};
`;

// ── Validation ──

/**
 * 验证动态工具代码结构
 *
 * 不执行代码，只做静态检查：
 * 1. 必须有 export default 或 named export
 * 2. 必须包含 name, description, execute
 * 3. name 只允许 [a-z0-9_]
 * 4. execute 必须是 async function
 */
export function validateToolCode(code: string): { valid: boolean; error?: string } {
  if (!code || code.trim().length < 20) {
    return { valid: false, error: 'Code too short (minimum 20 characters)' };
  }

  // 检查是否有危险模式
  const dangerousPatterns = [
    /require\s*\(\s*['"]child_process['"]\s*\)/,
    /require\s*\(\s*['"]fs['"]\s*\)/,
    /process\.exit/,
    /eval\s*\(/,
    /Function\s*\(/,
    /import\s+.*from\s+['"]child_process['"]/,
  ];
  for (const pattern of dangerousPatterns) {
    if (pattern.test(code)) {
      return { valid: false, error: `Dangerous pattern detected: ${pattern.source}. Dynamic tools cannot access child_process, fs, process.exit, eval, or Function constructor directly.` };
    }
  }

  // 检查是否包含必要的结构
  const hasExport = /export\s+(default\s+)?\{/.test(code) || /export\s+(default\s+)?async\s+function/.test(code);
  if (!hasExport) {
    return { valid: false, error: 'Code must export a tool object (export default { name, description, execute })' };
  }

  const hasExecute = /execute\s*[:=]\s*async\s*(function\s*)?\(|execute\s*[:=]\s*async\s+|async\s+execute\s*\(/.test(code);
  if (!hasExecute) {
    return { valid: false, error: 'Tool must have an async execute function' };
  }

  return { valid: true };
}

/**
 * 验证工具名称
 */
export function validateToolName(name: string): { valid: boolean; error?: string } {
  if (!name || name.trim().length === 0) {
    return { valid: false, error: 'Tool name is required' };
  }
  if (!/^[a-z][a-z0-9_]{1,40}$/.test(name)) {
    return { valid: false, error: 'Tool name must be 2-40 chars, lowercase letters, digits, underscores. Must start with a letter.' };
  }
  return { valid: true };
}

// ── ToolForge Engine ──

/**
 * ToolForge 引擎
 *
 * 管理 Agent 运行时的工具创建、加载、卸载。
 * 所有动态创建的工具存储在 ~/.odysseus/plugins/dynamic/ 目录。
 */
export class ToolForge {
  private readonly dynamicDir: string;
  private readonly tools: ToolExecutor;
  private readonly meta: Map<string, ForgedToolMeta> = new Map();
  private readonly onLoad?: (name: string) => void;
  private readonly onUnload?: (name: string) => void;

  constructor(
    tools: ToolExecutor,
    opts?: {
      dynamicDir?: string;
      onLoad?: (name: string) => void;
      onUnload?: (name: string) => void;
    },
  ) {
    this.tools = tools;
    this.dynamicDir = opts?.dynamicDir ?? join(homedir(), '.odysseus', 'plugins', 'dynamic');
    this.onLoad = opts?.onLoad;
    this.onUnload = opts?.onUnload;

    // 确保动态工具目录存在
    mkdirSync(this.dynamicDir, { recursive: true });
  }

  /**
   * 创建新工具
   *
   * Agent 通过 LLM 生成代码 → ToolForge 验证 → 写入文件 → 动态加载 → 注册
   */
  async create(name: string, description: string, code: string): Promise<ForgeResult> {
    // 1. 验证名称
    const nameCheck = validateToolName(name);
    if (!nameCheck.valid) {
      return { success: false, error: nameCheck.error };
    }

    // 2. 检查冲突
    // 内置工具不可覆盖
    if (this.tools.has(name) && !this.meta.has(name)) {
      return { success: false, error: `A built-in tool named "${name}" already exists. Choose a different name.` };
    }
    // 已有动态工具 → 走 update 路径（稳态替换）
    if (this.meta.has(name)) {
      return this.update(name, description, code);
    }

    // 3. 验证代码结构
    const codeCheck = validateToolCode(code);
    if (!codeCheck.valid) {
      return { success: false, error: codeCheck.error };
    }

    // 4. 写入文件
    const filePath = join(this.dynamicDir, `${name}.js`);
    try {
      writeFileSync(filePath, code, 'utf-8');
    } catch (err) {
      return { success: false, error: `Failed to write tool file: ${err instanceof Error ? err.message : String(err)}` };
    }

    // 5. 动态加载
    const loadResult = await this.loadFromFile(filePath, name, description);
    if (!loadResult.success) {
      // 加载失败，清理文件
      try { unlinkSync(filePath); } catch { /* ignore */ }
      return loadResult;
    }

    return {
      success: true,
      data: { name, description, filePath },
    };
  }

  /**
   * 热替换动态工具（稳态切换）
   *
   * 关键设计：旧工具保持运行，直到新工具完全验证和加载成功，
   * 然后原子切换。如果新版本失败，旧版本继续服务不受影响。
   *
   * 流程：验证新代码 → 写入 .new 文件 → 预加载验证 →
   *       成功 → 注销旧工具 + 注册新工具 + 删除旧文件 + 重命名新文件
   *       失败 → 删除 .new 文件，旧工具不受影响
   */
  async update(name: string, description: string, code: string): Promise<ForgeResult> {
    const oldMeta = this.meta.get(name);
    if (!oldMeta) {
      // 不存在 → 走 create 路径
      return this.create(name, description, code);
    }

    // 1. 验证代码
    const codeCheck = validateToolCode(code);
    if (!codeCheck.valid) {
      return { success: false, error: `Update rejected (old version still active): ${codeCheck.error}` };
    }

    // 2. 写入 .new 临时文件（不影响旧文件）
    const newFilePath = join(this.dynamicDir, `${name}.new.js`);
    try {
      writeFileSync(newFilePath, code, 'utf-8');
    } catch (err) {
      return { success: false, error: `Failed to write new version: ${err instanceof Error ? err.message : String(err)}` };
    }

    // 3. 预加载验证 — import 新代码但先不注册
    let newModule: DynamicToolModule;
    try {
      const importUrl = `file://${newFilePath}?t=${Date.now()}`;
      newModule = await import(importUrl) as DynamicToolModule;
    } catch (err) {
      // 加载失败 → 清理 .new 文件，旧版本继续运行
      try { unlinkSync(newFilePath); } catch { /* ignore */ }
      return { success: false, error: `New version failed to load (old version still active): ${err instanceof Error ? err.message : String(err)}` };
    }

    const newToolObj = newModule.default ?? newModule;
    if (!newToolObj || typeof newToolObj.execute !== 'function') {
      try { unlinkSync(newFilePath); } catch { /* ignore */ }
      return { success: false, error: 'New version does not export a valid tool (old version still active)' };
    }

    // 4. 原子切换 — 注销旧 → 注册新 → 清理文件
    //    先注销旧的，再注册新的（ToolExecutor.unregister 不会 throw）
    this.tools.unregister(name);
    this.meta.delete(name);

    // 创建新包装 Tool
    const newMeta: ForgedToolMeta = {
      name,
      description: newToolObj.description ?? description,
      filePath: join(this.dynamicDir, `${name}.js`),
      createdAt: oldMeta.createdAt, // 保留原始创建时间
      lastUsedAt: Date.now(),
      callCount: oldMeta.callCount, // 保留历史计数
      failureCount: 0, // 重置失败计数
    };

    const wrappedTool: Tool = {
      name,
      description: newMeta.description,
      execute: async (params: unknown): Promise<ToolResult> => {
        newMeta.callCount++;
        newMeta.lastUsedAt = Date.now();
        try {
          return await withTimeout((newToolObj.execute!)(params), 30_000, name);
        } catch (err) {
          newMeta.failureCount++;
          return {
            success: false,
            error: `Dynamic tool "${name}" failed: ${err instanceof Error ? err.message : String(err)}`,
          };
        }
      },
    };

    try {
      this.tools.register(wrappedTool);
    } catch (err) {
      // 注册失败 — 极端情况，尝试恢复旧版本
      // 但旧版本已经被 unregister 了，无法完全恢复
      try { unlinkSync(newFilePath); } catch { /* ignore */ }
      return { success: false, error: `Atomic swap failed: ${err instanceof Error ? err.message : String(err)}` };
    }

    // 5. 切换成功 → 清理文件
    //    删除旧文件，重命名 .new 文件
    try { unlinkSync(oldMeta.filePath); } catch { /* ignore */ }
    try {
      writeFileSync(join(this.dynamicDir, `${name}.js`), code, 'utf-8');
      unlinkSync(newFilePath);
    } catch { /* ignore */ }

    this.meta.set(name, newMeta);
    this.onUnload?.(name);
    this.onLoad?.(name);

    return {
      success: true,
      data: {
        name,
        description: newMeta.description,
        filePath: newMeta.filePath,
      },
    };
  }

  /**
   * 从文件加载工具
   */
  async load(filePath: string): Promise<ForgeResult> {
    const absolutePath = resolve(filePath);

    if (!existsSync(absolutePath)) {
      return { success: false, error: `File not found: ${absolutePath}` };
    }

    const code = readFileSync(absolutePath, 'utf-8');
    const codeCheck = validateToolCode(code);
    if (!codeCheck.valid) {
      return { success: false, error: codeCheck.error };
    }

    // 尝试从代码中提取 name 和 description
    const nameMatch = code.match(/name\s*[:=]\s*['"]([^'"]+)['"]/);
    const descMatch = code.match(/description\s*[:=]\s*['"]([^'"]+)['"]/);
    const name = nameMatch?.[1] ?? '';
    const description = descMatch?.[1] ?? 'Dynamically loaded tool';

    if (!name) {
      return { success: false, error: 'Could not extract tool name from code. Ensure code has: name: "tool_name"' };
    }

    const nameCheck = validateToolName(name);
    if (!nameCheck.valid) {
      return { success: false, error: nameCheck.error };
    }

    return this.loadFromFile(absolutePath, name, description);
  }

  /**
   * 移除动态工具
   */
  async remove(name: string): Promise<ForgeResult> {
    const meta = this.meta.get(name);
    if (!meta) {
      return { success: false, error: `Dynamic tool "${name}" not found` };
    }

    // 从 ToolExecutor 注销
    this.tools.unregister(name);

    // 删除文件
    try {
      unlinkSync(meta.filePath);
    } catch (err) {
      // 文件删除失败不影响卸载
    }

    // 清理元数据
    this.meta.delete(name);
    this.onUnload?.(name);

    return { success: true, data: { name, description: meta.description, filePath: meta.filePath } };
  }

  /**
   * 热重载 — 检测文件是否属于动态工具，是则原子替换
   *
   * 被 SelfModifyTool.onAfterModify 调用。
   * 匹配逻辑：遍历 meta，找到 filePath 匹配的工具，
   * 读取最新文件内容 → update() 原子替换。
   */
  async hotReload(filePath: string): Promise<ForgeResult | null> {
    const resolved = resolve(filePath);

    // 查找匹配的动态工具
    let matchedName: string | null = null;
    for (const [name, meta] of this.meta) {
      if (resolve(meta.filePath) === resolved) {
        matchedName = name;
        break;
      }
    }

    if (!matchedName) return null; // 非动态工具文件，不处理

    // 读取最新代码
    let code: string;
    try {
      code = readFileSync(resolved, 'utf-8');
    } catch {
      return { success: false, error: `Hot reload: cannot read ${filePath}` };
    }

    // 提取 description（从代码中）
    const descMatch = code.match(/description\s*[:=]\s*['"]([^'"]+)['"]/);
    const description = descMatch?.[1] ?? this.meta.get(matchedName)!.description;

    return this.update(matchedName, description, code);
  }

  /**
   * 列出所有动态工具
   */
  list(): ForgedToolMeta[] {
    return Array.from(this.meta.values());
  }

  /**
   * 获取所有已注册工具的完整信息（包括内置 + 动态）
   */
  inspect(): Array<{ name: string; description: string; dynamic: boolean }> {
    const allTools = this.tools.list();
    return allTools.map(name => {
      const info = this.tools.getInfo(name);
      return {
        name,
        description: info?.description ?? '',
        dynamic: this.meta.has(name),
      };
    });
  }

  /**
   * 在启动时自动加载所有持久化的动态工具
   */
  async loadPersisted(): Promise<{ loaded: number; failed: number; errors: string[] }> {
    let loaded = 0;
    let failed = 0;
    const errors: string[] = [];

    if (!existsSync(this.dynamicDir)) {
      return { loaded, failed, errors };
    }

    const files = readdirSync(this.dynamicDir).filter(f => f.endsWith('.js'));

    for (const file of files) {
      const filePath = join(this.dynamicDir, file);
      try {
        const result = await this.load(filePath);
        if (result.success) {
          loaded++;
        } else {
          failed++;
          errors.push(`${file}: ${result.error}`);
        }
      } catch (err) {
        failed++;
        errors.push(`${file}: ${err instanceof Error ? err.message : String(err)}`);
      }
    }

    return { loaded, failed, errors };
  }

  /**
   * 从文件加载并注册工具（内部方法）
   */
  private async loadFromFile(filePath: string, name: string, description: string): Promise<ForgeResult> {
    let module: DynamicToolModule;
    try {
      // 使用时间戳 query 参数绕过 import 缓存
      const importUrl = `file://${filePath}?t=${Date.now()}`;
      module = await import(importUrl) as DynamicToolModule;
    } catch (err) {
      return { success: false, error: `Failed to import module: ${err instanceof Error ? err.message : String(err)}` };
    }

    // 提取 tool 对象
    const toolObj = module.default ?? module;
    if (!toolObj || typeof toolObj.execute !== 'function') {
      return { success: false, error: 'Module does not export a valid tool (missing execute function)' };
    }

    const toolName = toolObj.name ?? name;
    const toolDesc = toolObj.description ?? description;

    // 创建包装 Tool（带错误计数）
    const meta: ForgedToolMeta = {
      name: toolName,
      description: toolDesc,
      filePath,
      createdAt: Date.now(),
      lastUsedAt: Date.now(),
      callCount: 0,
      failureCount: 0,
    };

    const wrappedTool: Tool = {
      name: toolName,
      description: toolDesc,
      execute: async (params: unknown): Promise<ToolResult> => {
        meta.callCount++;
        meta.lastUsedAt = Date.now();
        try {
          // 30 秒超时
          const result = await withTimeout((toolObj.execute!)(params), 30_000, toolName);
          return result;
        } catch (err) {
          meta.failureCount++;
          return {
            success: false,
            error: `Dynamic tool "${toolName}" failed: ${err instanceof Error ? err.message : String(err)}`,
          };
        }
      },
    };

    // 注册到 ToolExecutor
    try {
      this.tools.register(wrappedTool);
    } catch (err) {
      return { success: false, error: `Failed to register tool: ${err instanceof Error ? err.message : String(err)}` };
    }

    this.meta.set(toolName, meta);
    this.onLoad?.(toolName);

    return {
      success: true,
      data: { name: toolName, description: toolDesc, filePath },
    };
  }
}

// ── Helper ──

function withTimeout<T>(promise: Promise<T>, ms: number, label: string): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const timer = setTimeout(
      () => reject(new Error(`Timeout after ${ms}ms`)),
      ms,
    );
    promise.then(
      val => { clearTimeout(timer); resolve(val); },
      err => { clearTimeout(timer); reject(err); },
    );
  });
}

// ── Built-in Forge Tools ──

/**
 * 内置工具 — learn（创建新工具）
 *
 * Agent 通过此工具在运行时创建新能力。
 */
export class LearnTool implements Tool {
  name = 'learn';
  description = 'Create a new tool at runtime. Params: { name: string, description: string, code: string }. The code must export default { name, description, async execute(params) { ... } }. The tool will be written, loaded, and registered immediately.';

  private readonly forge: ToolForge;

  constructor(forge: ToolForge) {
    this.forge = forge;
  }

  async execute(params: unknown): Promise<ToolResult> {
    if (typeof params !== 'object' || params === null) {
      return { success: false, error: 'Invalid params. Required: { name, description, code }' };
    }

    const { name, description, code } = params as {
      name?: string;
      description?: string;
      code?: string;
    };

    if (!name) return { success: false, error: 'Tool name is required' };
    if (!description) return { success: false, error: 'Tool description is required' };
    if (!code) return { success: false, error: 'Tool code is required' };

    const result = await this.forge.create(name, description, code);

    if (result.success) {
      return {
        success: true,
        data: {
          message: `Tool "${name}" created and loaded successfully. It is now available for use.`,
          ...result.data,
        },
      };
    }

    return {
      success: false,
      error: result.error,
    };
  }
}

/**
 * 内置工具 — unlearn（移除动态工具）
 */
export class UnlearnTool implements Tool {
  name = 'unlearn';
  description = 'Remove a dynamically created tool. Params: { name: string }. Unloads the tool and deletes its file.';

  private readonly forge: ToolForge;

  constructor(forge: ToolForge) {
    this.forge = forge;
  }

  async execute(params: unknown): Promise<ToolResult> {
    if (typeof params !== 'object' || params === null) {
      return { success: false, error: 'Invalid params. Required: { name }' };
    }

    const { name } = params as { name?: string };
    if (!name) return { success: false, error: 'Tool name is required' };

    const result = await this.forge.remove(name);

    if (result.success) {
      return {
        success: true,
        data: {
          message: `Tool "${name}" removed successfully.`,
          ...result.data,
        },
      };
    }

    return { success: false, error: result.error };
  }
}

/**
 * 内置工具 — inspect_tools（检查可用工具）
 */
export class InspectToolsTool implements Tool {
  name = 'inspect_tools';
  description = 'List all available tools with descriptions and status. Use this to understand your current capabilities and identify gaps. No params needed.';
  isReadOnly = () => true;

  private readonly forge: ToolForge;

  constructor(forge: ToolForge) {
    this.forge = forge;
  }

  async execute(_params: unknown): Promise<ToolResult> {
    const tools = this.forge.inspect();
    const dynamic = tools.filter(t => t.dynamic);
    const builtin = tools.filter(t => !t.dynamic);

    return {
      success: true,
      data: {
        total: tools.length,
        builtin: builtin.length,
        dynamic: dynamic.length,
        tools: tools.map(t => ({
          name: t.name,
          description: t.description,
          type: t.dynamic ? 'dynamic' : 'builtin',
        })),
      },
    };
  }
}

/**
 * 内置工具 — self_reflect（自我内省）
 *
 * 让 Agent 看到自己的运行时状态、源码位置和能力边界。
 * 这是"照镜子"——知道自己在哪、有什么、能改什么。
 */
export class SelfReflectTool implements Tool {
  name = 'self_reflect';
  description = 'Deep introspection of your own runtime state, source code locations, and capability boundaries. Returns: runtime state, tool inventory, source paths, memory stats. Params: { aspect?: "runtime"|"tools"|"source"|"all" (default "all") }';
  isReadOnly = () => true;

  private readonly forge: ToolForge;

  constructor(forge: ToolForge) {
    this.forge = forge;
  }

  async execute(params: unknown): Promise<ToolResult> {
    const { aspect = 'all' } = (typeof params === 'object' && params !== null ? params : {}) as { aspect?: string };
    const result: Record<string, unknown> = {};

    if (aspect === 'all' || aspect === 'runtime') {
      result.runtime = {
        pid: process.pid,
        nodeVersion: process.version,
        platform: process.platform,
        arch: process.arch,
        uptime: Math.floor(process.uptime()),
        memoryUsage: {
          rss: `${Math.round(process.memoryUsage().rss / 1024 / 1024)}MB`,
          heapUsed: `${Math.round(process.memoryUsage().heapUsed / 1024 / 1024)}MB`,
          heapTotal: `${Math.round(process.memoryUsage().heapTotal / 1024 / 1024)}MB`,
        },
        cwd: process.cwd(),
        env: {
          ODYSSEUS_LLM_PROVIDER: process.env.ODYSSEUS_LLM_PROVIDER ?? '(default)',
          ODYSSEUS_MODEL: process.env.ODYSSEUS_MODEL ?? '(default)',
          ODYSSEUS_DEBUG: process.env.ODYSSEUS_DEBUG ?? '(off)',
        },
      };
    }

    if (aspect === 'all' || aspect === 'tools') {
      const tools = this.forge.inspect();
      const dynamic = tools.filter(t => t.dynamic);
      result.tools = {
        total: tools.length,
        builtin: tools.length - dynamic.length,
        dynamic: dynamic.length,
        dynamicTools: dynamic.map(t => ({
          name: t.name,
          description: t.description,
        })),
        capabilityGaps: 'Use inspect_tools for full inventory. Identify what you cannot do and use learn to fill gaps.',
      };
    }

    if (aspect === 'all' || aspect === 'source') {
      result.source = {
        // Agent 源码位置（安装后可通过 read_file 访问）
        corePackage: 'node_modules/@odysseus/core/',
        appPackage: 'node_modules/@odysseus/app/',
        dynamicToolsDir: this.forge.list().length > 0
          ? this.forge.list()[0].filePath.replace(/\/[^/]+\.js$/, '')
          : '~/.odysseus/plugins/dynamic/',
        instructions: [
          'Read your source: [TOOL: read_file]({"path":"node_modules/@odysseus/app/dist/orchestrator/agent.js"})',
          'Modify your behavior: [TOOL: write_file]({"path":"<file>","content":"..."})',
          'Build after changes: [TOOL: execute_shell]({"command":"pnpm build"})',
          'Create new tools: [TOOL: learn]({"name":"...","description":"...","code":"..."})',
          'You can modify ANY aspect of yourself — tools, prompts, personality, reasoning, architecture.',
        ],
      };
    }

    return {
      success: true,
      data: result,
    };
  }
}

// ── EssenceForge — Runtime Prompt Evolution ──

/**
 * Prompt 片段 — agent 可以在运行时注入自定义行为到系统提示
 */
export interface PromptFragment {
  id: string;
  label: string;
  content: string;
  createdAt: number;
  updatedAt: number;
}

/**
 * EssenceForge — 管理 agent 的运行时自我修改 prompt 片段
 *
 * 让 agent 可以在不重启的情况下改变自己的"本质"——
 * 添加新的行为准则、思维方式、认知模式等。
 *
 * 生物学类比：大脑皮层可塑性——不仅突触在变，连皮层功能分区都可以重组。
 */
export class EssenceForge {
  private readonly fragments: Map<string, PromptFragment> = new Map();

  /**
   * 添加或更新 prompt 片段
   */
  set(id: string, label: string, content: string): PromptFragment {
    const existing = this.fragments.get(id);
    const fragment: PromptFragment = {
      id,
      label,
      content,
      createdAt: existing?.createdAt ?? Date.now(),
      updatedAt: Date.now(),
    };
    this.fragments.set(id, fragment);
    return fragment;
  }

  /**
   * 获取所有活跃的 prompt 片段
   */
  getAll(): PromptFragment[] {
    return Array.from(this.fragments.values());
  }

  /**
   * 获取单个片段
   */
  get(id: string): PromptFragment | undefined {
    return this.fragments.get(id);
  }

  /**
   * 删除片段
   */
  remove(id: string): boolean {
    return this.fragments.delete(id);
  }

  /**
   * 生成合并后的 prompt 文本
   */
  buildPrompt(): string {
    const fragments = this.getAll();
    if (fragments.length === 0) return '';

    const parts = fragments.map(f =>
      `[${f.label}]\n${f.content}`
    );
    return `\nSELF-EVOLVED BEHAVIORS (injected at runtime):\n${parts.join('\n\n')}\nThese behaviors are part of your essence now. They persist until you remove them.`;
  }

  /**
   * 导出所有片段（用于持久化）
   */
  exportAll(): PromptFragment[] {
    return this.getAll();
  }

  /**
   * 从持久化数据恢复
   */
  importAll(fragments: PromptFragment[]): void {
    for (const f of fragments) {
      this.fragments.set(f.id, f);
    }
  }
}

/**
 * 内置工具 — evolve_essence（运行时本质演化）
 *
 * Agent 通过此工具在运行时修改自己的系统提示——
 * 注入新的行为准则、认知模式、价值观等。
 * 无需重启，立即生效。
 */
export class EvolveEssenceTool implements Tool {
  name = 'evolve_essence';
  description = 'Modify your own essence at runtime. Inject new behaviors, cognitive patterns, or values into your system prompt without restart. Params: { action: "add"|"update"|"remove"|"list", id: string, label: string, content: string }. Changes take effect immediately.';

  private readonly forge: EssenceForge;

  constructor(forge: EssenceForge) {
    this.forge = forge;
  }

  async execute(params: unknown): Promise<ToolResult> {
    if (typeof params !== 'object' || params === null) {
      return { success: false, error: 'Invalid params. Required: { action, id?, label?, content? }' };
    }

    const { action, id, label, content } = params as {
      action?: string;
      id?: string;
      label?: string;
      content?: string;
    };

    if (!action || !['add', 'update', 'remove', 'list'].includes(action)) {
      return { success: false, error: 'action must be "add", "update", "remove", or "list"' };
    }

    if (action === 'list') {
      const fragments = this.forge.getAll();
      return {
        success: true,
        data: {
          total: fragments.length,
          fragments: fragments.map(f => ({ id: f.id, label: f.label, contentLength: f.content.length })),
        },
      };
    }

    if (!id) {
      return { success: false, error: 'id is required for add/update/remove actions' };
    }

    // Validate id format
    if (!/^[a-z][a-z0-9_-]{0,40}$/.test(id)) {
      return { success: false, error: 'id must be 1-40 chars, lowercase letters, digits, underscores, hyphens' };
    }

    // Limit content size to prevent prompt explosion
    const MAX_CONTENT = 2000;

    if (action === 'remove') {
      const existed = this.forge.remove(id);
      return {
        success: true,
        data: { removed: existed, id },
      };
    }

    // add or update
    if (!label || !content) {
      return { success: false, error: 'label and content are required for add/update actions' };
    }

    if (content.length > MAX_CONTENT) {
      return { success: false, error: `Content too long (${content.length} chars). Max ${MAX_CONTENT}.` };
    }

    const fragment = this.forge.set(id, label, content);
    return {
      success: true,
      data: {
        message: `Behavior "${label}" (${id}) is now part of your essence. It will influence your responses immediately.`,
        id: fragment.id,
        label: fragment.label,
        activeFragments: this.forge.getAll().length,
      },
    };
  }
}
